# Generated by Django 6.0 on 2025-12-21 17:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="RatioView",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="State",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("abbreviation", models.CharField(max_length=2, unique=True)),
                (
                    "day_threshold",
                    models.PositiveIntegerField(
                        help_text="Number of days before tax residency is triggered"
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Office",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("latitude", models.DecimalField(decimal_places=14, max_digits=17)),
                ("longitude", models.DecimalField(decimal_places=14, max_digits=17)),
                ("address", models.TextField(blank=True)),
                (
                    "state",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="offices",
                        to="tracker.state",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Day",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(unique=True)),
                (
                    "day_type",
                    models.CharField(
                        choices=[
                            ("WORK", "Standard Workday"),
                            ("PTO_WORK", "PTO Workday Mix"),
                            ("HOLIDAY", "Company Holiday"),
                        ],
                        default="WORK",
                        max_length=10,
                    ),
                ),
                ("note", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "office",
                    models.ForeignKey(
                        blank=True,
                        help_text="Office worked from (if applicable)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="days",
                        to="tracker.office",
                    ),
                ),
                (
                    "states",
                    models.ManyToManyField(
                        help_text="States this day counts toward",
                        related_name="days",
                        to="tracker.state",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Days",
                "ordering": ["-date"],
            },
        ),
    ]
