# Generated by Django 6.0 on 2025-12-22 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="office",
            name="place_id",
            field=models.CharField(
                blank=True,
                help_text="Google maps PlaceID, if available",
                max_length=255,
                null=True,
                unique=True,
            ),
        ),
    ]
