# Generated by Django 6.0 on 2025-12-25 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0002_office_place_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="state",
            name="is_active",
            field=models.BooleanField(
                default=False,
                help_text="Whether this state is actively tracked by the user",
            ),
        ),
        migrations.AlterField(
            model_name="day",
            name="day_type",
            field=models.CharField(
                choices=[
                    ("WORK", "Standard Workday"),
                    ("PTO_WORK", "PTO Workday Mix"),
                    ("HOLIDAY", "Company Holiday on which we worked"),
                ],
                default="WORK",
                max_length=10,
            ),
        ),
    ]
