# Generated by Django 6.0 on 2026-02-18 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0003_state_is_active_alter_day_day_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="ratioview",
            name="hidden",
            field=models.BooleanField(
                default=False, help_text="Hide this ratio view from the list"
            ),
        ),
    ]
